"""
Validation tests comparing Python outputs with C++ reference files.

These tests run the Python validation demos and compare their HDF5 outputs
with the reference files generated by the C++ Samurai demos.

Usage:
    # Run validation tests with default tolerance (1e-10)
    pytest tests/test_validation.py -v

    # Run with custom tolerance
    pytest tests/test_validation.py --val-tol 1e-10 -v

    # Generate Python reference files (for debugging)
    pytest tests/test_validation.py --val-generate-ref -v
"""

import shutil
from pathlib import Path

import pytest

from sampai.utils.io import compare

from tests.validation_demos import advection_1d, advection_2d, burgers_1d, scalar_burgers_2d


# ============================================================================
# Fixtures to run each demo once and share results
# ============================================================================

@pytest.fixture(scope="class")
def advection_1d_output(val_output_dir, val_generate_ref):
    """Run 1D advection demo once for all tests in the class."""
    output_dir = advection_1d.run_advection_1d(Tf=0.1, output_path=val_output_dir)
    return output_dir


@pytest.fixture(scope="class")
def advection_2d_output(val_output_dir, val_generate_ref):
    """Run 2D advection demo once for all tests in the class."""
    output_dir = advection_2d.run_advection_2d(Tf=0.01, output_path=val_output_dir)
    return output_dir


@pytest.fixture(scope="class")
def burgers_1d_output(val_output_dir, val_generate_ref):
    """Run 1D Burgers demo once for all tests in the class."""
    output_dir = burgers_1d.run_burgers_1d(Tf=0.1, output_path=val_output_dir)
    return output_dir


@pytest.fixture(scope="class")
def scalar_burgers_2d_output(val_output_dir, val_generate_ref):
    """Run 2D scalar Burgers demo once for all tests in the class."""
    output_dir = scalar_burgers_2d.run_scalar_burgers_2d(Tf=0.001, output_path=val_output_dir)
    return output_dir


# ============================================================================
# Test classes using shared fixtures
# ============================================================================

@pytest.mark.requires_cpp_references
class TestAdvection1D:
    """Test 1D advection against C++ reference."""

    def test_advection_1d_init(
        self, advection_1d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 1D advection initial state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = advection_1d_output

        # Compare with C++ reference
        # C++ reference: test_finite_volume_demo_finite-volume-advection-1d-0.1_init.h5
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-advection-1d-0.1_init.h5"
        # Python now uses C++ naming: test_finite_volume_demo_finite-volume-advection-1d-0.1_init.h5
        test_file = output_dir / "test_finite_volume_demo_finite-volume-advection-1d-0.1_init.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"

    def test_advection_1d_final(
        self, advection_1d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 1D advection final state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = advection_1d_output

        # Compare with C++ reference
        # C++ reference: test_finite_volume_demo_finite-volume-advection-1d-0.1.h5
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-advection-1d-0.1.h5"
        # Python now uses C++ naming: test_finite_volume_demo_finite-volume-advection-1d-0.1.h5
        test_file = output_dir / "test_finite_volume_demo_finite-volume-advection-1d-0.1.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"


@pytest.mark.requires_cpp_references
class TestAdvection2D:
    """Test 2D advection against C++ reference."""

    def test_advection_2d_init(
        self, advection_2d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 2D advection initial state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = advection_2d_output

        # Compare with C++ reference
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-advection-2d-0.01_init.h5"
        test_file = output_dir / "test_finite_volume_demo_finite-volume-advection-2d-0.01_init.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"

    def test_advection_2d_final(
        self, advection_2d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 2D advection final state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = advection_2d_output

        # Compare with C++ reference
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-advection-2d-0.01.h5"
        test_file = output_dir / "test_finite_volume_demo_finite-volume-advection-2d-0.01.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"


@pytest.mark.requires_cpp_references
class TestBurgers1D:
    """Test 1D Burgers against C++ reference."""

    def test_burgers_1d_final(
        self, burgers_1d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 1D Burgers final state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = burgers_1d_output

        # Compare with C++ reference
        ref_file = cpp_reference_dir / "test_finite_volume_demo_burgers.h5"
        test_file = output_dir / "test_finite_volume_demo_burgers.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"


@pytest.mark.requires_cpp_references
class TestScalarBurgers2D:
    """Test 2D scalar Burgers against C++ reference."""

    def test_scalar_burgers_2d_init(
        self, scalar_burgers_2d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 2D scalar Burgers initial state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = scalar_burgers_2d_output

        # Compare with C++ reference
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-scalar-burgers-2d-0.001_init.h5"
        test_file = output_dir / "test_finite_volume_demo_finite-volume-scalar-burgers-2d-0.001_init.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"

    def test_scalar_burgers_2d_final(
        self, scalar_burgers_2d_output, val_generate_ref, val_tol, cpp_reference_dir
    ):
        """Test 2D scalar Burgers final state."""
        if val_generate_ref:
            pytest.skip("Skipping comparison when generating reference files")

        output_dir = scalar_burgers_2d_output

        # Compare with C++ reference
        ref_file = cpp_reference_dir / "test_finite_volume_demo_finite-volume-scalar-burgers-2d-0.001.h5"
        test_file = output_dir / "test_finite_volume_demo_finite-volume-scalar-burgers-2d-0.001.h5"

        assert ref_file.exists(), f"C++ reference file not found: {ref_file}"
        assert test_file.exists(), f"Python output file not found: {test_file}"

        identical = compare.compare_hdf5_files(
            str(test_file), str(ref_file), tol=val_tol, verbose=True
        )
        assert identical, f"Python and C++ outputs differ beyond tolerance {val_tol}"


class TestGenerateReference:
    """Tests for generating Python reference files."""

    def test_generate_advection_1d_reference(self, val_output_dir, val_generate_ref):
        """Generate Python reference files for 1D advection."""
        if not val_generate_ref:
            pytest.skip("Use --val-generate-ref to generate reference files")

        # Run Python demo to generate reference files
        output_dir = advection_1d.run_advection_1d(
            Tf=0.1, output_path=val_output_dir
        )

        # Copy files to reference directory
        for f in output_dir.glob("*.h5"):
            shutil.copy(f, val_output_dir / f.name)

        pytest.skip(f"Reference files generated in {val_output_dir}")

    def test_generate_advection_2d_reference(self, val_output_dir, val_generate_ref):
        """Generate Python reference files for 2D advection."""
        if not val_generate_ref:
            pytest.skip("Use --val-generate-ref to generate reference files")

        # Run Python demo to generate reference files
        output_dir = advection_2d.run_advection_2d(
            Tf=0.01, output_path=val_output_dir
        )

        # Copy files to reference directory
        for f in output_dir.glob("*.h5"):
            shutil.copy(f, val_output_dir / f.name)

        pytest.skip(f"Reference files generated in {val_output_dir}")

    def test_generate_burgers_1d_reference(self, val_output_dir, val_generate_ref):
        """Generate Python reference files for 1D Burgers."""
        if not val_generate_ref:
            pytest.skip("Use --val-generate-ref to generate reference files")

        # Run Python demo to generate reference files
        output_dir = burgers_1d.run_burgers_1d(
            Tf=0.1, output_path=val_output_dir
        )

        # Copy files to reference directory
        for f in output_dir.glob("*.h5"):
            shutil.copy(f, val_output_dir / f.name)

        pytest.skip(f"Reference files generated in {val_output_dir}")

    def test_generate_scalar_burgers_2d_reference(self, val_output_dir, val_generate_ref):
        """Generate Python reference files for 2D scalar Burgers."""
        if not val_generate_ref:
            pytest.skip("Use --val-generate-ref to generate reference files")

        # Run Python demo to generate reference files
        output_dir = scalar_burgers_2d.run_scalar_burgers_2d(
            Tf=0.001, output_path=val_output_dir
        )

        # Copy files to reference directory
        for f in output_dir.glob("*.h5"):
            shutil.copy(f, val_output_dir / f.name)

        pytest.skip(f"Reference files generated in {val_output_dir}")
